GET http://localhost:8080/hello
#Accept: application/json

> {%
// client.test("test-hello", function() {
//   client.log("test/hello");
//   client.log(response.body);
//   client.log(JSON.stringify(response.body));
//   client.assert(response.status === 200, "not 200");
//   client.assert(response.body === "Hello World", "test failed");
// });
%}
###

POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

POST http://localhost:8080/test/list