package com.zhenxiao.wiki.util;

import org.springframework.stereotype.Component;

import java.text.ParseException;

//Snowflake algorithm for distributed ID generation

/**
 * It divides 64-bit bits into several parts in the way of namespace partition,
 * each part represents different meanings. The 64-bit integer in Java is Long type,
 * so the ID generated by SnowFlake algorithm in Java is long to store.
 */

@Component
public class SnowFlake {

    //Start Time Stamp
    private final static long START_STMP = 1609459200000L; // 2021-01-01 00:00:00

    //How much bit each section takes up
    private final static long SEQUENCE_BIT = 12; //sequence number bits
    private final static long MACHINE_BIT = 5;   //machine id bits (2^5 = 32 machines)
    private final static long DATACENTER_BIT = 5; //datacenter bits, 32 datacenters

    ///Maximum value of each section
    private final static long MAX_DATACENTER_NUM = -1L ^ (-1L << DATACENTER_BIT);
    private final static long MAX_MACHINE_NUM = -1L ^ (-1L << MACHINE_BIT);
    private final static long MAX_SEQUENCE = -1L ^ (-1L << SEQUENCE_BIT);

    //Shifting left for very section
    private final static long MACHINE_LEFT = SEQUENCE_BIT;
    private final static long DATACENTER_LEFT = SEQUENCE_BIT + MACHINE_BIT;
    private final static long TIMESTMP_LEFT = DATACENTER_LEFT + DATACENTER_BIT;

    //
    private long datacenterId = 1;  //datacenter
    private long machineId = 1;     //machine id
    private long sequence = 0L; //sequence id
    private long lastStmp = -1L;//last time stamp

    public SnowFlake() {
    }

    public SnowFlake(long datacenterId, long machineId) {
        if (datacenterId > MAX_DATACENTER_NUM || datacenterId < 0) {
            throw new IllegalArgumentException("datacenterId can't be greater than MAX_DATACENTER_NUM or less than 0");
        }
        if (machineId > MAX_MACHINE_NUM || machineId < 0) {
            throw new IllegalArgumentException("machineId can't be greater than MAX_MACHINE_NUM or less than 0");
        }
        this.datacenterId = datacenterId;
        this.machineId = machineId;
    }

    /**
     * generate next ID
     *
     * @return
     */
    public synchronized long nextId() {
        long currStmp = getNewstmp();
        if (currStmp < lastStmp) {
            throw new RuntimeException("Clock moved backwards.  Refusing to generate id");
        }

        if (currStmp == lastStmp) {
            //auto increment sequence number within the same millisecond
            sequence = (sequence + 1) & MAX_SEQUENCE;
            //sequence number reaches maximum within the same millisecond
            if (sequence == 0L) {
                currStmp = getNextMill();
            }
        } else {
            //not within the same millisecond
            sequence = 0L;
        }

        lastStmp = currStmp;

        return (currStmp - START_STMP) << TIMESTMP_LEFT //timestamp
                | datacenterId << DATACENTER_LEFT       //data center
                | machineId << MACHINE_LEFT             //machine id
                | sequence;                             //sequence number
    }

    private long getNextMill() {
        long mill = getNewstmp();
        while (mill <= lastStmp) {
            mill = getNewstmp();
        }
        return mill;
    }

    private long getNewstmp() {
        return System.currentTimeMillis();
    }

    public static void main(String[] args) throws ParseException {
        // new snowflake instance
        SnowFlake snowFlake = new SnowFlake(1, 1);

        long start = System.currentTimeMillis();
        for (int i = 0; i < 10; i++) {
            System.out.println(snowFlake.nextId());
            System.out.println(System.currentTimeMillis() - start);
        }
    }
}
